batch_size: 4
num_workers: 4
epochs: 100
test_interval: 10
save_model: True
model_save_path: saved_models/${experiment_name}

train_data_folder_list:
  - "D4"
  - "D9"
test_data_folder_list:
  - "D7"
